[package]
name = "falcon-2"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
bitvec = "1.0.1"
futures = "0.3.31"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tinyset = "0.5.2"

[profile.profiling]
inherits = "release"
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1